# Generated by Django 6.0.2 on 2026-02-11 03:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='granted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permission',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado')], default='pendiente', max_length=20),
        ),
    ]
