# Generated by Django 6.0.2 on 2026-02-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_permission_granted_at_permission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
